# Generated by Django 5.1.4 on 2024-12-29 15:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='Device Name')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_before_normalization', models.FloatField(verbose_name='Average Before Normalization')),
                ('average_after_normalization', models.FloatField(verbose_name='Average After Normalization')),
                ('data_size', models.IntegerField(verbose_name='Data Size')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elements.device', verbose_name='Device ID')),
            ],
        ),
    ]
