# Generated by Django 5.1.4 on 2024-12-29 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='device_id',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='element',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_device', to='elements.device'),
        ),
    ]
